name: Deploy Playground
on:
  release:
    types:
      - published
      - prereleased
      - released

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        run: |
          curl https://api.render.com/deploy/$RENDER_TOKEN
